const hobbies = [
  { id: 1, name: "Acrobatics" },
  { id: 2, name: "Acting" },
  { id: 3, name: "Air sports" },
  { id: 4, name: "Airsoft" },
  { id: 5, name: "Amateur astronomy" },
  { id: 6, name: "Amateur geology" },
  { id: 7, name: "Amateur radio" },
  { id: 8, name: "American football" },
  { id: 9, name: "Animal fancy" },
  { id: 10, name: "Antiquing" },
  { id: 11, name: "Antiquities" },
  { id: 12, name: "Aquascaping" },
  { id: 13, name: "Archery" },
  { id: 14, name: "Art collecting" },
  { id: 15, name: "Astrology" },
  { id: 16, name: "Astronomy" },
  { id: 17, name: "Audiophile" },
  { id: 18, name: "Australian rules football" },
  { id: 19, name: "Auto audiophilia" },
  { id: 20, name: "Auto racing" },
  { id: 21, name: "Backpacking" },
  { id: 22, name: "Badminton" },
  { id: 23, name: "Baking" },
  { id: 24, name: "Baseball" },
  { id: 25, name: "Basketball" },
  { id: 26, name: "Baton twirling" },
  { id: 27, name: "Baton twirling" },
  { id: 28, name: "Beach volleyball" },
  { id: 29, name: "Beadwork" },
  { id: 30, name: "Beatboxing" },
  { id: 31, name: "Beekeeping" },
  { id: 32, name: "Beer brewing" },
  { id: 33, name: "Bird watching" },
  { id: 34, name: "Birdwatching" },
  { id: 35, name: "Blacksmithing" },
  { id: 36, name: "BMX" },
  { id: 37, name: "Board games" },
  { id: 38, name: "Board sports" },
  { id: 39, name: "Bodybuilding" },
  { id: 40, name: "Bonsai" },
  { id: 41, name: "Book collecting" },
  { id: 42, name: "Book restoration" },
  { id: 43, name: "Bowling" },
  { id: 44, name: "Boxing" },
  { id: 45, name: "Brazilian jiu-jitsu" },
  { id: 46, name: "Breakdancing" },
  { id: 47, name: "Bridge" },
  { id: 48, name: "Building" },
  { id: 49, name: "Bullet journaling" },
  { id: 50, name: "Bus spotting" },
  { id: 51, name: "Camping" },
  { id: 52, name: "Candle making" },
  { id: 53, name: "Canoeing" },
  { id: 54, name: "Cartooning" },
  { id: 55, name: "Carving" },
  { id: 56, name: "Casino gambling" },
  { id: 57, name: "Caving" },
  { id: 58, name: "Cheerleading" },
  { id: 59, name: "Chess" },
  { id: 60, name: "Cigar smoking" },
  { id: 61, name: "Climbing" },
  { id: 62, name: "Clothesmaking" },
  { id: 63, name: "Coasteering" },
  { id: 64, name: "Collecting" },
  { id: 65, name: "Color guard" },
  { id: 66, name: "Coloring" },
  { id: 67, name: "Comic book collecting" },
  { id: 68, name: "Composting" },
  { id: 69, name: "Computer programming" },
  { id: 70, name: "Confectionery" },
  { id: 71, name: "Cooking" },
  { id: 72, name: "Cosplaying" },
  { id: 73, name: "Couponing" },
  { id: 74, name: "Craft" },
  { id: 75, name: "Creative writing" },
  { id: 76, name: "Cricket" },
  { id: 77, name: "Crocheting" },
  { id: 78, name: "Cross-stitch" },
  { id: 79, name: "Crossword puzzles" },
  { id: 80, name: "Cryptography" },
  { id: 81, name: "Curling" },
  { id: 82, name: "Cycling" },
  { id: 83, name: "Dance" },
  { id: 84, name: "Darts" },
  { id: 85, name: "Debate" },
  { id: 86, name: "Decorating" },
  { id: 87, name: "Deltiology" },
  { id: 88, name: "Die-cast toy" },
  { id: 89, name: "Digital arts" },
  { id: 90, name: "Dining" },
  { id: 91, name: "Diorama" },
  { id: 92, name: "Disc golf" },
  { id: 93, name: "Do it yourself" },
  { id: 94, name: "Dog sport" },
  { id: 95, name: "Dolls" },
  { id: 96, name: "Dowsing" },
  { id: 97, name: "Drama" },
  { id: 98, name: "Drawing" },
  { id: 99, name: "Drinking coffee" },
  { id: 100, name: "Driving" },
  { id: 101, name: "Drones" },
  { id: 102, name: "Eating" },
  { id: 103, name: "Element collecting" },
  { id: 104, name: "Embroidery" },
  { id: 105, name: "Entomology" },
  { id: 106, name: "Ephemera collecting" },
  { id: 107, name: "Equestrianism" },
  { id: 108, name: "Exercise" },
  { id: 109, name: "Exhibition drill" },
  { id: 110, name: "Experimenting" },
  { id: 111, name: "Falconry" },
  { id: 112, name: "Fantasy sports" },
  { id: 113, name: "Fashion" },
  { id: 114, name: "Fast cars" },
  { id: 115, name: "Felting" },
  { id: 116, name: "Fencing" },
  { id: 117, name: "Ferret" },
  { id: 118, name: "Field hockey" },
  { id: 119, name: "Figure skating" },
  { id: 120, name: "Fishing" },
  { id: 121, name: "Fishkeeping" },
  { id: 122, name: "Flag football" },
  { id: 123, name: "Flower arranging" },
  { id: 124, name: "Flower collecting/pressing" },
  { id: 125, name: "Fly tying" },
  { id: 126, name: "Flying" },
  { id: 127, name: "Fossil hunting" },
  { id: 128, name: "Four-wheeling" },
  { id: 129, name: "Frisbee golf" },
  { id: 130, name: "Fruit collecting" },
  { id: 131, name: "Gardening" },
  { id: 132, name: "Genealogy" },
  { id: 133, name: "Geocaching" },
  { id: 134, name: "Ghost hunting" },
  { id: 135, name: "Glass art" },
  { id: 136, name: "Glassblowing" },
  { id: 137, name: "Glowsticking" },
  { id: 138, name: "Gnoming" },
  { id: 139, name: "Go" },
  { id: 140, name: "Go Kart Racing" },
  { id: 141, name: "Going to movies" },
  { id: 142, name: "Golf" },
  { id: 143, name: "Gongoozling" },
  { id: 144, name: "Graffiti" },
  { id: 145, name: "Gymnastics" },
  { id: 146, name: "Gun collecting" },
  { id: 147, name: "Gunsmithing" },
  { id: 148, name: "Gym" },
  { id: 149, name: "Handball" },
  { id: 150, name: "Hiking" },
  { id: 151, name: "Homebrewing" },
  { id: 152, name: "Hooping" },
  { id: 153, name: "Horseback riding" },
  { id: 154, name: "Hula hooping" },
  { id: 155, name: "Hunting" },
  { id: 156, name: "Ice hockey" },
  { id: 157, name: "Ice skating" },
  { id: 158, name: "Improving Mindfulness" },
  { id: 159, name: "Inline skating" },
  { id: 160, name: "Insect collecting" },
  { id: 161, name: "Jigsaw puzzles" },
  { id: 162, name: "Jogging" },
  { id: 163, name: "Judo" },
  { id: 164, name: "Juggling" },
  { id: 165, name: "Jukskei" },
  { id: 166, name: "Jump Roping" },
  { id: 167, name: "Kabaddi" },
  { id: 168, name: "Kart racing" },
  { id: 169, name: "Kayaking" },
  { id: 170, name: "Kite flying" },
  { id: 171, name: "Kite surfing" },
  { id: 172, name: "Kombucha brewing" },
  { id: 173, name: "Knife making" },
  { id: 174, name: "Knapping" },
  { id: 175, name: "Knife making" },
  { id: 176, name: "Knife throwing" },
  { id: 177, name: "Krav Maga" },
  { id: 178, name: "Lacemaking" },
  { id: 179, name: "Lacrosse" },
  { id: 180, name: "Lapidary" },
  { id: 181, name: "Larping" },
  { id: 182, name: "Laser tag" },
  { id: 183, name: "Lawn darts" },
  { id: 184, name: "Learning" },
  { id: 185, name: "Learning Foreign Language" },
  { id: 186, name: "Learning An Instrument" },
  { id: 187, name: "Leather crafting" },
  { id: 188, name: "Lego building" },
  { id: 189, name: "Letterboxing" },
  { id: 190, name: "Listening to music" },
  { id: 191, name: "Locksport" },
  { id: 192, name: "LARPing" },
  { id: 193, name: "Machining" },
  { id: 194, name: "Macrame" },
  { id: 195, name: "Magic" },
  { id: 196, name: "Mahjong" },
  { id: 197, name: "Marbles" },
  { id: 198, name: "Martial arts" },
  { id: 199, name: "Metal detecting" },
  { id: 200, name: "Metalworking" },
  { id: 201, name: "Meteorology" },
  { id: 202, name: "Microscopy" },
  { id: 203, name: "Mineral collecting" },
  { id: 204, name: "Model aircraft" },
  { id: 205, name: "Model building" },
  { id: 206, name: "Model engineering" },
  { id: 207, name: "Model rockets" },
  { id: 208, name: "Modeling ships" },
  { id: 209, name: "Models" },
  { id: 210, name: "Motor sports" },
  { id: 211, name: "Motorcycling" },
  { id: 212, name: "Mountain biking" },
  { id: 213, name: "Mountaineering" },
  { id: 214, name: "Mushroom hunting" },
  { id: 215, name: "Mycology" },
  { id: 216, name: "Netball" },
  { id: 217, name: "Nordic skating" },
  { id: 218, name: "Orienteering" },
  { id: 219, name: "Origami" },
  { id: 220, name: "Owning An Antique Car" },
  { id: 221, name: "Paintball" },
  { id: 222, name: "Painting" },
  { id: 223, name: "Palmistry" },
  { id: 224, name: "Paragliding" },
  { id: 225, name: "Parasailing" },
  { id: 226, name: "Parkour" },
  { id: 227, name: "People watching" },
  { id: 228, name: "Photography" },
  { id: 229, name: "Playing music" },
  { id: 230, name: "Playing musical instruments" },
  { id: 231, name: "Poi" },
  { id: 232, name: "Poker" },
  { id: 233, name: "Pole dancing" },
  { id: 234, name: "Politics" },
  { id: 235, name: "Pottery" },
  { id: 236, name: "Powerlifting" },
  { id: 237, name: "Protesting" },
  { id: 238, name: "Puppetry" },
  { id: 239, name: "Pyrotechnics" },
  { id: 240, name: "Quilting" },
  { id: 241, name: "Racquetball" },
  { id: 242, name: "Radio-controlled car racing" },
  { id: 243, name: "Rafting" },
  { id: 244, name: "Railroad hobbies" },
  { id: 245, name: "Railway journeys" },
  { id: 246, name: "Rapping" },
  { id: 247, name: "Reading" },
  { id: 248, name: "Record collecting" },
  { id: 249, name: "Recreational mathematics" },
  { id: 250, name: "Reptile keeping" },
  { id: 251, name: "Research" },
  { id: 252, name: "Resin casting" },
  { id: 253, name: "Robot combat" },
  { id: 254, name: "Rock balancing" },
  { id: 255, name: "Rock climbing" },
  { id: 256, name: "Rock painting" },
  { id: 257, name: "Roleplaying" },
  { id: 258, name: "Roller derby" },
  { id: 259, name: "Roller skating" },
  { id: 260, name: "Rugby" },
  { id: 261, name: "Running" },
  { id: 262, name: "Sailing" },
  { id: 263, name: "Sand art" },
  { id: 264, name: "Scrapbooking" },
  { id: 265, name: "Scuba diving" },
  { id: 266, name: "Sculling or rowing" },
  { id: 267, name: "Sculpting" },
  { id: 268, name: "Sea glass collecting" },
  { id: 269, name: "Seashell collecting" },
  { id: 270, name: "Sewing" },
  { id: 271, name: "Shooting" },
  { id: 272, name: "Shopping" },
  { id: 273, name: "Shortwave listening" },
  { id: 274, name: "Singing" },
  { id: 275, name: "Skateboarding" },
  { id: 276, name: "Sketching" },
  { id: 277, name: "Skiing" },
  { id: 278, name: "Skimboarding" },
  { id: 279, name: "Skydiving" },
  { id: 280, name: "Slacklining" },
  { id: 281, name: "Slot car racing" },
  { id: 282, name: "Snorkeling" },
  { id: 283, name: "Snowboarding" },
  { id: 284, name: "Soapmaking" },
  { id: 285, name: "Soccer" },
  { id: 286, name: "Social media" },
  { id: 287, name: "Spelunking" },
  { id: 288, name: "Squash" },
  { id: 289, name: "Stamp collecting" },
  { id: 290, name: "Stand-up comedy" },
  { id: 291, name: "Stone collecting" },
  { id: 292, name: "Stone skipping" },
  { id: 293, name: "Studying" },
  { id: 294, name: "Sun bathing" },
  { id: 295, name: "Surfing" },
  { id: 296, name: "Survivalism" },
  { id: 297, name: "Swimming" },
  { id: 298, name: "Table football" },
  { id: 299, name: "Table tennis" },
  { id: 300, name: "Tai chi" },
  { id: 301, name: "Tapestry" },
  { id: 302, name: "Tarot" },
  { id: 303, name: "Taxidermy" },
  { id: 304, name: "Tea tasting" },
  { id: 305, name: "Tennis" },
  { id: 306, name: "Tesla coils" },
  { id: 307, name: "Tetris" },
  { id: 308, name: "Texting" },
  { id: 309, name: "Textiles" },
  { id: 310, name: "Theatre" },
  { id: 311, name: "Thrifting" },
  { id: 312, name: "Tool collecting" },
  { id: 313, name: "Tour skating" },
  { id: 314, name: "Trade fair visiting" },
  { id: 315, name: "Train collecting" },
  { id: 316, name: "Train spotting" },
  { id: 317, name: "Trainspotting" },
  { id: 318, name: "Traveling" },
  { id: 319, name: "Treasure hunting" },
  { id: 320, name: "Trekking" },
  { id: 321, name: "Triathlon" },
  { id: 322, name: "Tutoring children" },
  { id: 323, name: "Ultimate frisbee" },
  { id: 324, name: "Urban exploration" },
  { id: 325, name: "Vacation" },
  { id: 326, name: "Vehicle restoration" },
  { id: 327, name: "Video game collecting" },
  { id: 328, name: "Video gaming" },
  { id: 329, name: "Videophilia" },
  { id: 330, name: "Vintage cars" },
  { id: 331, name: "Violin" },
  { id: 332, name: "Volunteering" },
  { id: 333, name: "Walking" },
  { id: 334, name: "Warhammer" },
  { id: 335, name: "Watching movies" },
  { id: 336, name: "Watching television" },
  { id: 337, name: "Water sports" },
  { id: 338, name: "Weaving" },
  { id: 339, name: "Web surfing" },
  { id: 340, name: "Weightlifting" },
  { id: 341, name: "Windsurfing" },
  { id: 342, name: "Wine making" },
  { id: 343, name: "Wingsuit flying" },
  { id: 344, name: "Wood carving" },
  { id: 345, name: "Woodworking" },
  { id: 346, name: "Worldbuilding" },
  { id: 347, name: "Wrestling" },
  { id: 348, name: "Writing" },
  { id: 349, name: "Writing music" },
  { id: 350, name: "Yachting" },
  { id: 351, name: "Yoga" },
  { id: 352, name: "Yo-yoing" },
  { id: 353, name: "Ziplining" },
  { id: 354, name: "Zumba" },
];

export default hobbies;
